#ifndef LIBSOCIOPATHY_GLOBAL_H
#define LIBSOCIOPATHY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBSOCIOPATHY_LIBRARY)
#  define LIBSOCIOPATHYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBSOCIOPATHYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBSOCIOPATHY_GLOBAL_H
